### ISSUE TITLE
g15daemon stop working after few seconds

### ISSUE THREAD

**Issue by danja95** [berendt/g510s#1]
Hi,
i had compiled the code on my Ubuntu 18.04 LTS amd64 4.15.0-23-generic.

Everything is working, after a while with typing on the keyboard, sometimes the keyboard is stopping work or one key will pressed down until i killed the daemon or/and repluged the usb.

On daemon no error will show up.

Do you need more info? tell me.

Thanks in adavance.

**Comment by berendt** [comment]
@danieltech777 This repository has not been maintained for years and is here for historical reasons only. Unfortunately, I can not help you there.

**Comment by VincentSC** [comment]
Then please leave the issues open and put this on the readme, so others know what's the status
